name: Update AT host

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  update:
    name: Update AT host

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch latest AT host
        run: |
          wget https://nordicsemiconductor.github.io/at_host-hex/at_host-thingy91_nrf9160_ns.hex -O at_host/thingy91_at_host_increased_buf.hex
          wget https://nordicsemiconductor.github.io/at_host-hex/at_host-nrf9160dk_nrf9160_ns.hex -O at_host/91dk_at_host_increased_buf.hex
          if [[ `git status --porcelain` ]]; then
            echo "HAS_CHANGES=1" >> $GITHUB_ENV
            git status
          else
            echo "HAS_CHANGES=0" >> $GITHUB_ENV
            echo "No changes."
          fi

      - name: Commit changes
        if: env.HAS_CHANGES == '1'
        run: |
          echo "machine github.com login accesskey password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
          git config --global user.email "actions@example.com"
          git config --global user.name "github-actions[bot]"
          git add at_host
          git commit -m "fix(at_host): update at_host"
          git push

      - name: Install dependencies
        run: npm ci --no-audit
        if: env.HAS_CHANGES == '1'

      - name: Compile source
        run: npx tsc
        if: env.HAS_CHANGES == '1'

      - name: Run tests
        run: npm test
        if: env.HAS_CHANGES == '1'

      - name: Publish release
        run: npx semantic-release
        if: env.HAS_CHANGES == '1'
